basedir = '/HapCHAT'
datadir =  '/data'
core =  basedir + '/software/hapchat/hapchat'
hapchat =  '/HapCHAT.py'

# master rule
rule master :
	input :
		datadir + '/out.phased.vcf',
		datadir + '/out.realigned.phased.vcf'

# auxiliary rules
#----------------------------------------------------------------------

rule run_hapchat :
	input :
		bam = datadir + '/file.bam',
		vcf = datadir + '/file.vcf',
		core = core # just to ensure that it exists before running

	output : datadir + '/out.phased.vcf'

	shell : '{hapchat} {input.vcf} {input.bam} > {output}'

rule run_hapchat_realignment :
	input :
		bam = datadir + '/file.bam',
		vcf = datadir + '/file.vcf',
		fasta = datadir + '/genome.fasta',
		core = core
		
	output : datadir + '/out.realigned.phased.vcf'

	shell : '''

   {hapchat} --reference {input.fasta} \
      {input.vcf} {input.bam} > {output} '''

rule setup_hapchat :
	output : core
	shell : 'bash {basedir}/setup.sh'

rule download_reference :
	output :
		datadir + '/genome.fasta'

	shell : '''

   wget -O {output}.gz.incomplete ftp://ftp.ncbi.nlm.nih.gov/1000genomes/ftp/technical/reference/human_g1k_v37.fasta.gz
   mv {output}.gz.incomplete {output}.gz
   # gunzip fails with "decompression OK, trailing garbage ignored"
   # because the file is razf-compressed (gzip-compatible, but with an
   # index at end)
   gunzip -f {output}.gz || true
   md5sum -c {basedir}/data/MD5SUM '''

rule download_bam_vcf :
	input :
		bam = basedir + '/example/file.bam',
		vcf = basedir + '/example/file.vcf'
                
	output :
		bam = datadir + '/file.bam',
                vcf = datadir + '/file.vcf'

	shell : '''
   test -f {output.bam} || cp {input.bam} {datadir} && touch {output.bam}
   test -f {output.vcf} || cp {input.vcf} {datadir} && touch {output.vcf}
 '''
